# Drupal with PostgreSQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: example
# ADVANCED OPTIONS; Database host: postgres

version: '3.1'

services:

  drupal:
    container_name: drupal
    image: drupal:9-apache
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always
    depends_on:
      - drupaldb

  drupaldb:
    container_name: postgresdrupal
    image: postgres:10
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: ha
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - postgresdrupal:/var/lib/postgresql/data

volumes:
  postgresdrupal:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  
