version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    environment:
      - FB_NOAUTH=true
    ports:
      - 80:80
    volumes:
      - /filebrowser/:/srv
      - ./filebrowser.db:/database/filebrowser.db
      - ./filebrowser.json:/.filebrowser.json
