version: '3.8'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - grafana

volumes:
    prometheus_data:   
    grafana_data:  

networks:
  grafana:
    external:
      name: prometheus
