version: '3'

services:
  nextclouddb:
    container_name: nextclouddb
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    env_file:
      - db.env
    networks:
      - nextcloud
      - adminer

  nextcloudredis:
    container_name: nextcloudredis
    image: redis:alpine
    restart: always
    networks:
      - nextcloud

  app:
    container_name: nextcloud
    image: nextcloud:apache
    restart: always
    ports:
      - "8088:80"
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=nextcloudredis
    env_file:
      - db.env
    depends_on:
      - nextclouddb
      - nextcloudredis
    networks:
      - nextcloud

  cron:
    container_name: nextcloudcron
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextclouddb
      - nextcloudredis
    networks:
      - nextcloud

volumes:
  db:
  nextcloud:

networks:
  nextcloud:
    name: nextcloud
    driver: bridge
  adminer:
    external:
      name: adminer

