version: '3.1'

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: mariadb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    networks:
      - adminer
networks:
  adminer:
    external:
      name: adminer
