version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    # user/password:  admin/password
    command: --admin-password "$$2y$$05$$BwROGrCmVbcCBRc.Ot0fSe/59CygRBXVjin0rWGOoW5l4.CeBXFjm" -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

