version: '3.8'

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=passwordpassword
    volumes:
      - timescaledb:/var/lib/postgresql/data
    networks:
      - timescaledb

volumes:
  timescaledb:

networks:
  timescaledb:
    name: timescaledb
    driver: bridge
